# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e27043b41f132daedb515113cee38e385fcf8e7c357b797a540b2723f32f43281dcc4a8666c1f9ce534075109389c47072ccbd1a274a2886a1733578357f7f8

test:
  secret_key_base: f988821064b3b98aa49ae690eeb136ffc73ee072a5cb44f37f1ccb0f79cee69c01903c7028dbaa776eada1f41773688ac76316d672e6930e46b05929a6f77647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
